import { TypeRegistry } from "@smithy/core/schema";
import type { StaticErrorSchema, StaticOperationSchema, StaticStructureSchema, StaticUnionSchema } from "@smithy/types";
export declare var StediServiceException$: StaticErrorSchema;
export declare var ClaimEditException$: StaticErrorSchema;
export declare var InternalFailureException$: StaticErrorSchema;
export declare var AuthenticationFailedException$: StaticErrorSchema;
export declare var ConflictException$: StaticErrorSchema;
export declare var ForbiddenException$: StaticErrorSchema;
export declare var InternalServerException$: StaticErrorSchema;
export declare var InvalidRequestException$: StaticErrorSchema;
export declare var NotFoundException$: StaticErrorSchema;
export declare var TooManyRequestsException$: StaticErrorSchema;
/**
 * TypeRegistry instances containing modeled errors.
 * @internal
 *
 */
export declare const errorTypeRegistries: TypeRegistry[];
export declare var ClaimEditError$: StaticStructureSchema;
export declare var CreateProfessionalClaimSubmissionInput$: StaticStructureSchema;
export declare var CreateProfessionalClaimSubmissionOutput$: StaticStructureSchema;
export declare var GetProfessionalClaimSubmissionInput$: StaticStructureSchema;
export declare var GetProfessionalClaimSubmissionOutput$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionAddress$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionAttachment$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionAuthorization$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionBilling$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionBillingProvider$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionBillingProviderIdentifiers$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionClinicalDates$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionContact$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionData$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionDateRange$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionDrugIdentification$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionEncounter$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionInsured$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionOrderingProvider$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionOrderingProviderIdentifiers$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionOtherInsured$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionOtherInsuredAuthorization$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionOtherPayer$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionPatient$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionPatientCondition$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionPayer$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionPersonName$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionProcedureCode$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionReferenceNumbers$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionReferringProvider$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionReferringProviderIdentifiers$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionRenderingProvider$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionRenderingProviderIdentifiers$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionResubmission$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionServiceFacility$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionServiceFacilityIdentifiers$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionServiceLine$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionServiceLinePriorAuthorizationNumber$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionSubmitter$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionSupervisingProvider$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionSupervisingProviderIdentifiers$: StaticStructureSchema;
export declare var ValidateProfessionalClaimSubmissionInput$: StaticStructureSchema;
export declare var ValidateProfessionalClaimSubmissionOutput$: StaticStructureSchema;
export declare var ValidationFailure$: StaticStructureSchema;
export declare var ProfessionalClaimSubmissionClaimNote$: StaticUnionSchema;
export declare var ProfessionalClaimSubmissionOtherPayerId$: StaticUnionSchema;
export declare var ProfessionalClaimSubmissionPrescriptionOrCompoundDrugAssociationNumber$: StaticUnionSchema;
export declare var ProfessionalClaimSubmissionQualifiedName$: StaticUnionSchema;
export declare var ProfessionalClaimSubmissionQualifiedOrganizationName$: StaticUnionSchema;
export declare var ProfessionalClaimSubmissionQualifiedPersonName$: StaticUnionSchema;
export declare var ProfessionalClaimSubmissionTaxId$: StaticUnionSchema;
export declare var CreateProfessionalClaimSubmission$: StaticOperationSchema;
export declare var GetProfessionalClaimSubmission$: StaticOperationSchema;
export declare var ValidateProfessionalClaimSubmission$: StaticOperationSchema;
