# Code generated by smithy-python-codegen DO NOT EDIT.

__version__: str = "1.0.0"

__doc__ = """The Stedi SDK for Python.

Each operation takes its input model from ``stedi.models``::

    from stedi import Config, Stedi

    async with Stedi(Config(api_key="...")) as client:
        result = await client.create_professional_claim_submission(claim)

See https://www.stedi.com/docs for the fields each operation requires.
"""

from typing import Self

from smithy_core.exceptions import CallError
from smithy_core.retries import RetryStrategyOptions

from .client import Stedi as _Stedi
from .config import Config

__all__ = ["CallError", "Config", "RetryStrategyOptions", "Stedi", "__version__"]

class Stedi(_Stedi):
    """The Stedi SDK client.

    Construct inside a running event loop (e.g. via ``asyncio.run``) and use as an async
    context manager.
    """

    async def aclose(self) -> None:
        # Close the shared session only if this SDK opened it; a caller's transport is theirs to close.
        transport = getattr(self._config, "transport", None)
        if getattr(transport, "owns_session", False):
            session = getattr(transport, "_session", None)
            if session is not None and not session.closed:
                await session.close()

    async def __aenter__(self) -> Self:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()
