# Code generated by smithy-python-codegen DO NOT EDIT.

# Session-leak-safe aiohttp transport for the Stedi client.
from __future__ import annotations

from typing import Any

from smithy_http.aio.aiohttp import AIOHTTPClient

class SharedAIOHTTPClient(AIOHTTPClient):
    """An ``AIOHTTPClient`` that shares a single HTTP session across copies of the client
    configuration, instead of opening a new (never-closed) session for each request.

    ``owns_session`` is True only when this SDK opened the session (safe to close on exit); False
    for a caller-supplied session, which the caller owns."""

    owns_session: bool = False

    def __deepcopy__(self, memo: dict[int, object]) -> SharedAIOHTTPClient:
        return self

def default_transport(transport: Any) -> Any:
    """Return ``transport`` made safe to share across per-request copies of the configuration:

    - ``None`` -> a new ``SharedAIOHTTPClient`` that owns its session (the default transport);
    - a plain ``AIOHTTPClient`` -> wrapped as a ``SharedAIOHTTPClient`` that keeps the given
      client's configuration and session (preserving any TLS/proxy/session settings); the
      caller still owns that session;
    - any other transport (already shared, or non-aiohttp) -> returned unchanged."""
    if transport is None:
        client = SharedAIOHTTPClient()
        client.owns_session = True
        return client
    if isinstance(transport, AIOHTTPClient) and not isinstance(transport, SharedAIOHTTPClient):
        return SharedAIOHTTPClient(client_config=transport._config, _session=transport._session)
    return transport
