# Code generated by smithy-python-codegen DO NOT EDIT.

# Stedi SDK User-Agent interceptor.
from __future__ import annotations

import platform
from typing import Any

from smithy_core.interceptors import Interceptor, RequestContext
from smithy_http import Field
from smithy_http.aio.interfaces import HTTPRequest

from stedi import __version__

_USER_AGENT = f"stedi-sdk-python/{__version__} python/{platform.python_version()}"

class StediUserAgentInterceptor(Interceptor[Any, Any, HTTPRequest, None]):
    def modify_before_signing(self, context: RequestContext[Any, HTTPRequest]) -> HTTPRequest:
        request = context.transport_request
        request.fields.set_field(Field(name="User-Agent", values=[_USER_AGENT]))
        request.fields.set_field(Field(name="Stedi-Agent", values=[_USER_AGENT]))
        return request

def stedi_user_agent_plugin(config: Any) -> None:
    config.interceptors.append(StediUserAgentInterceptor())
