# Code generated by smithy-python-codegen DO NOT EDIT.

# Per-operation endpoint routing for the Stedi client.
from __future__ import annotations

from typing import Any

from smithy_core import URI
from smithy_core.endpoints import Endpoint, EndpointResolverParams, resolve_static_uri
from smithy_core.exceptions import EndpointResolutionError
from smithy_core.interfaces import Endpoint as _Endpoint

_HOSTS: dict[str, str] = {
    "CreateEventDestination": "events.us.stedi.com",
    "CreateProfessionalClaimSubmission": "claims.us.stedi.com",
    "DeleteEventDestination": "events.us.stedi.com",
    "GetClaim": "claims.us.stedi.com",
    "GetClaimTimeline": "claims.us.stedi.com",
    "GetEventDestination": "events.us.stedi.com",
    "GetEventDestinationEvent": "events.us.stedi.com",
    "GetEventDestinationSecret": "events.us.stedi.com",
    "GetProfessionalClaimSubmission": "claims.us.stedi.com",
    "ListClaims": "claims.us.stedi.com",
    "ListEventDestinationEvents": "events.us.stedi.com",
    "ListEventDestinations": "events.us.stedi.com",
    "RotateEventDestinationSecret": "events.us.stedi.com",
    "UpdateEventDestination": "events.us.stedi.com",
    "ValidateProfessionalClaimSubmission": "claims.us.stedi.com",
}

class StediEndpointResolver:
    """Routes each operation to its backend host; honors an endpoint_uri override."""

    async def resolve_endpoint(self, params: EndpointResolverParams[Any]) -> _Endpoint:
        override = resolve_static_uri(params)
        if override is not None:
            return Endpoint(uri=override)
        op_name = params.operation.schema.id.name
        host = _HOSTS.get(op_name)
        if host is None:
            raise EndpointResolutionError(
                f"No Stedi endpoint mapping for operation {op_name!r}"
            )
        return Endpoint(uri=URI(host=host, scheme="https"))
