# Code generated by smithy-python-codegen DO NOT EDIT.

from copy import deepcopy
import logging

from smithy_core.aio.client import ClientCall, RequestPipeline
from smithy_core.aio.retries import RetryStrategyResolver
from smithy_core.exceptions import ExpectationNotMetError
from smithy_core.interceptors import InterceptorChain
from smithy_core.types import TypedProperties
from smithy_http.plugins import user_agent_plugin

from ._stedi_user_agent import stedi_user_agent_plugin
from .config import Config, Plugin
from .models import (
    CREATE_PROFESSIONAL_CLAIM_SUBMISSION,
    CreateProfessionalClaimSubmissionInput,
    CreateProfessionalClaimSubmissionOutput,
    GET_PROFESSIONAL_CLAIM_SUBMISSION,
    GetProfessionalClaimSubmissionInput,
    GetProfessionalClaimSubmissionOutput,
    VALIDATE_PROFESSIONAL_CLAIM_SUBMISSION,
    ValidateProfessionalClaimSubmissionInput,
    ValidateProfessionalClaimSubmissionOutput,
)



logger = logging.getLogger(__name__)

class Stedi:
    """The Stedi SDK --- unified, typed access to Stedi's healthcare APIs.    """
    def __init__(self, config: Config | None = None, plugins: list[Plugin] | None = None):
        """
    Constructor for `Stedi`.

    Args:
        config:
            Optional configuration for the client. Here you can set things like
            the endpoint for HTTP services or auth credentials.
        plugins:
            A list of callables that modify the configuration dynamically. These
            can be used to set defaults, for example.
    """
        self._config = config or Config()

        client_plugins: list[Plugin] = [
            user_agent_plugin,
    stedi_user_agent_plugin,
        ]
        if plugins:
            client_plugins.extend(plugins)

        for plugin in client_plugins:
            plugin(self._config)

        self._retry_strategy_resolver = RetryStrategyResolver()

    async def create_professional_claim_submission(
        self,
        input: CreateProfessionalClaimSubmissionInput,
        plugins: list[Plugin] | None = None
    ) -> CreateProfessionalClaimSubmissionOutput:
        """
        Submit a professional claim using the Stedi JSON format.

        Args:
            input:
                An instance of `CreateProfessionalClaimSubmissionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `CreateProfessionalClaimSubmissionOutput`.
        """
        operation_plugins: list[Plugin] = [

        ]
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError("protocol and transport MUST be set on the config to make calls.")

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(
            protocol=config.protocol,
            transport=config.transport
        )
        call = ClientCall(
            input=input,
            operation=CREATE_PROFESSIONAL_CLAIM_SUBMISSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def get_professional_claim_submission(
        self,
        input: GetProfessionalClaimSubmissionInput,
        plugins: list[Plugin] | None = None
    ) -> GetProfessionalClaimSubmissionOutput:
        """
        Fetch a professional claim submission by ID.

        Args:
            input:
                An instance of `GetProfessionalClaimSubmissionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `GetProfessionalClaimSubmissionOutput`.
        """
        operation_plugins: list[Plugin] = [

        ]
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError("protocol and transport MUST be set on the config to make calls.")

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(
            protocol=config.protocol,
            transport=config.transport
        )
        call = ClientCall(
            input=input,
            operation=GET_PROFESSIONAL_CLAIM_SUBMISSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)

    async def validate_professional_claim_submission(
        self,
        input: ValidateProfessionalClaimSubmissionInput,
        plugins: list[Plugin] | None = None
    ) -> ValidateProfessionalClaimSubmissionOutput:
        """
        Validate a professional claim in the Stedi JSON format without
        submitting it.

        Args:
            input:
                An instance of `ValidateProfessionalClaimSubmissionInput`.
            plugins:
                A list of callables that modify the configuration dynamically.
                Changes made by these plugins only apply for the duration of the
                operation execution and will not affect any other operation
                invocations.

        Returns:
            An instance of `ValidateProfessionalClaimSubmissionOutput`.
        """
        operation_plugins: list[Plugin] = [

        ]
        if plugins:
            operation_plugins.extend(plugins)
        config = deepcopy(self._config)
        for plugin in operation_plugins:
            plugin(config)
        if config.protocol is None or config.transport is None:
            raise ExpectationNotMetError("protocol and transport MUST be set on the config to make calls.")

        retry_strategy = await self._retry_strategy_resolver.resolve_retry_strategy(
            retry_strategy=config.retry_strategy
        )

        pipeline = RequestPipeline(
            protocol=config.protocol,
            transport=config.transport
        )
        call = ClientCall(
            input=input,
            operation=VALIDATE_PROFESSIONAL_CLAIM_SUBMISSION,
            context=TypedProperties({"config": config}),
            interceptor=InterceptorChain(config.interceptors),
            auth_scheme_resolver=config.auth_scheme_resolver,
            supported_auth_schemes=config.auth_schemes,
            endpoint_resolver=config.endpoint_resolver,
            retry_strategy=retry_strategy,
        )

        return await pipeline(call)
