# Code generated by smithy-python-codegen DO NOT EDIT.

from dataclasses import dataclass
from typing import Any, Callable, TypeAlias, Union

from smithy_aws_core.aio.protocols import RestJsonClientProtocol
from smithy_core.aio.endpoints import StaticEndpointResolver
from smithy_core.aio.interfaces import (
    ClientProtocol,
    ClientTransport,
    EndpointResolver,
)
from smithy_core.aio.interfaces.auth import AuthScheme
from smithy_core.aio.interfaces.identity import IdentityResolver
from smithy_core.aio.interfaces.retries import RetryStrategy
from smithy_core.interceptors import Interceptor
from smithy_core.interfaces import URI
from smithy_core.retries import RetryStrategyOptions
from smithy_core.shapes import ShapeID
from smithy_core.traits import APIKeyLocation
from smithy_http.aio.aiohttp import AIOHTTPClient
from smithy_http.aio.auth.apikey import APIKeyAuthScheme
from smithy_http.aio.identity.apikey import (
    APIKeyIdentity,
    APIKeyIdentityProperties,
    APIKeyIdentityResolver,
)
from smithy_http.interfaces import HTTPRequestConfiguration

from ._private.schemas import STEDI as _SCHEMA_STEDI
from ._stedi_endpoints import StediEndpointResolver
from ._stedi_transport import default_transport
from .auth import HTTPAuthSchemeResolver
from .models import (
    CreateEligibilityCheckInput,
    CreateEligibilityCheckOutput,
    CreateEventDestinationInput,
    CreateEventDestinationOutput,
    CreateProfessionalClaimSubmissionInput,
    CreateProfessionalClaimSubmissionOutput,
    DeleteEventDestinationInput,
    DeleteEventDestinationOutput,
    GetClaimInput,
    GetClaimOutput,
    GetClaimTimelineInput,
    GetClaimTimelineOutput,
    GetEventDestinationEventInput,
    GetEventDestinationEventOutput,
    GetEventDestinationInput,
    GetEventDestinationOutput,
    GetEventDestinationSecretInput,
    GetEventDestinationSecretOutput,
    GetProfessionalClaimSubmissionInput,
    GetProfessionalClaimSubmissionOutput,
    ListClaimsInput,
    ListClaimsOutput,
    ListEventDestinationEventsInput,
    ListEventDestinationEventsOutput,
    ListEventDestinationsInput,
    ListEventDestinationsOutput,
    RotateEventDestinationSecretInput,
    RotateEventDestinationSecretOutput,
    UpdateEventDestinationInput,
    UpdateEventDestinationOutput,
    ValidateProfessionalClaimSubmissionInput,
    ValidateProfessionalClaimSubmissionOutput,
)


_ServiceInterceptor = Union[Interceptor[CreateProfessionalClaimSubmissionInput, CreateProfessionalClaimSubmissionOutput, Any, Any], Interceptor[GetProfessionalClaimSubmissionInput, GetProfessionalClaimSubmissionOutput, Any, Any], Interceptor[ValidateProfessionalClaimSubmissionInput, ValidateProfessionalClaimSubmissionOutput, Any, Any], Interceptor[GetClaimInput, GetClaimOutput, Any, Any], Interceptor[GetClaimTimelineInput, GetClaimTimelineOutput, Any, Any], Interceptor[ListClaimsInput, ListClaimsOutput, Any, Any], Interceptor[CreateEligibilityCheckInput, CreateEligibilityCheckOutput, Any, Any], Interceptor[CreateEventDestinationInput, CreateEventDestinationOutput, Any, Any], Interceptor[DeleteEventDestinationInput, DeleteEventDestinationOutput, Any, Any], Interceptor[GetEventDestinationInput, GetEventDestinationOutput, Any, Any], Interceptor[GetEventDestinationEventInput, GetEventDestinationEventOutput, Any, Any], Interceptor[GetEventDestinationSecretInput, GetEventDestinationSecretOutput, Any, Any], Interceptor[ListEventDestinationEventsInput, ListEventDestinationEventsOutput, Any, Any], Interceptor[ListEventDestinationsInput, ListEventDestinationsOutput, Any, Any], Interceptor[RotateEventDestinationSecretInput, RotateEventDestinationSecretOutput, Any, Any], Interceptor[UpdateEventDestinationInput, UpdateEventDestinationOutput, Any, Any]]
@dataclass(init=False)
class Config:
    """Configuration for Stedi."""

    api_key: str | None
    """The API key to send along with requests."""

    api_key_identity_resolver: IdentityResolver[APIKeyIdentity, APIKeyIdentityProperties] | None
    """Resolves the API key."""

    auth_scheme_resolver: HTTPAuthSchemeResolver
    """
    An auth scheme resolver that determines the auth scheme for each
    operation.
    """

    auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]]
    """A map of auth scheme ids to auth schemes."""

    endpoint_resolver: EndpointResolver
    """
    The endpoint resolver used to resolve the final endpoint per-operation
    based on the configuration.
    """

    endpoint_uri: str | URI | None
    """A static URI to route requests to."""

    http_request_config: HTTPRequestConfiguration | None
    """Configuration for individual HTTP requests."""

    interceptors: list[_ServiceInterceptor]
    """
    The list of interceptors, which are hooks that are called during the
    execution of a request.
    """

    protocol: ClientProtocol[Any, Any] | None
    """The protocol to serialize and deserialize requests with."""

    retry_strategy: RetryStrategy | RetryStrategyOptions | None
    """
    The retry strategy or options for configuring retry behavior. Can be
    either a configured RetryStrategy or RetryStrategyOptions to create one.
    """

    transport: ClientTransport[Any, Any] | None
    """The transport to use to send requests (e.g. an HTTP client)."""

    def __init__(
        self,
        *,
        api_key: str | None = None,
        api_key_identity_resolver: IdentityResolver[APIKeyIdentity, APIKeyIdentityProperties] | None = None,
        auth_scheme_resolver: HTTPAuthSchemeResolver | None = None,
        auth_schemes: dict[ShapeID, AuthScheme[Any, Any, Any, Any]] | None = None,
        endpoint_resolver: EndpointResolver | None = None,
        endpoint_uri: str | URI | None = None,
        http_request_config: HTTPRequestConfiguration | None = None,
        interceptors: list[_ServiceInterceptor] | None = None,
        protocol: ClientProtocol[Any, Any] | None = None,
        retry_strategy: RetryStrategy | RetryStrategyOptions | None = None,
        transport: ClientTransport[Any, Any] | None = None,
    ):
        self.api_key = api_key
        self.api_key_identity_resolver = api_key_identity_resolver if api_key_identity_resolver is not None else APIKeyIdentityResolver()
        self.auth_scheme_resolver = auth_scheme_resolver or HTTPAuthSchemeResolver()
        self.auth_schemes = auth_schemes or {
            ShapeID("smithy.api#httpApiKeyAuth"): APIKeyAuthScheme(
                                                                           name="Authorization",
                                                                           location=APIKeyLocation.HEADER,
                                                                           scheme="Key",
                                                                       )
            ,
        }
        self.endpoint_resolver = endpoint_resolver or StediEndpointResolver()
        self.endpoint_uri = endpoint_uri
        self.http_request_config = http_request_config
        self.interceptors = interceptors or []
        self.protocol = protocol or RestJsonClientProtocol(_SCHEMA_STEDI)
        self.retry_strategy = retry_strategy
        self.transport = default_transport(transport)

    def set_auth_scheme(self, scheme: AuthScheme[Any, Any, Any, Any]) -> None:
        """
        Sets the implementation of an auth scheme.

        Using this method ensures the correct key is used.

        Args:
            scheme:
                The auth scheme to add.
        """
        self.auth_schemes[scheme.scheme_id] = scheme

Plugin: TypeAlias = Callable[[Config], None]
"""A callable that allows customizing the config object on each request."""
