"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfessionalClaimSubmissionDrugIdentificationUnitOfMeasure = exports.ProfessionalClaimSubmissionPurpose = exports.ProfessionalClaimSubmissionPatientRelationshipToInsured = exports.ProfessionalClaimSubmissionResponsibilityLevel = exports.ProfessionalClaimSubmissionOtherInsuredRelationshipToInsured = exports.ProfessionalClaimSubmissionMedicareSecondaryInsuranceType = exports.ProfessionalClaimSubmissionClaimFilingIndicator = exports.ProfessionalClaimSubmissionPaymentResponsibilityLevelCode = exports.ProfessionalClaimSubmissionInsuranceType = exports.ProfessionalClaimSubmissionGenderCode = exports.ProfessionalClaimSubmissionClaimFrequencyCode = exports.ProfessionalClaimSubmissionEPSDTReferralConditionIndicator = exports.ProfessionalClaimSubmissionAttachmentTransmissionCode = exports.ProfessionalClaimSubmissionAttachmentReportTypeCode = exports.ProfessionalClaimSubmissionProviderSignature = exports.ProfessionalClaimSubmissionProviderAcceptsAssignment = exports.ProfessionalClaimSubmissionReleaseOfInformationCode = exports.ProfessionalClaimSubmissionBenefitsAssignmentCertificationIndicator = void 0;
exports.ProfessionalClaimSubmissionBenefitsAssignmentCertificationIndicator = {
    NO: "NO",
    NOT_APPLICABLE: "NOT_APPLICABLE",
    YES: "YES",
};
exports.ProfessionalClaimSubmissionReleaseOfInformationCode = {
    INFORMED_CONSENT: "INFORMED_CONSENT",
    YES: "YES",
};
exports.ProfessionalClaimSubmissionProviderAcceptsAssignment = {
    ASSIGNED: "ASSIGNED",
    CLINICAL_LAB_ONLY: "CLINICAL_LAB_ONLY",
    NOT_ASSIGNED: "NOT_ASSIGNED",
};
exports.ProfessionalClaimSubmissionProviderSignature = {
    NOT_ON_FILE: "NOT_ON_FILE",
    ON_FILE: "ON_FILE",
};
exports.ProfessionalClaimSubmissionAttachmentReportTypeCode = {
    ADMISSION_SUMMARY: "ADMISSION_SUMMARY",
    ALLERGIES_SENSITIVITIES: "ALLERGIES_SENSITIVITIES",
    AMBULANCE_CERTIFICATION: "AMBULANCE_CERTIFICATION",
    AUTOPSY_REPORT: "AUTOPSY_REPORT",
    BASELINE: "BASELINE",
    BENCHMARK_TESTING_RESULTS: "BENCHMARK_TESTING_RESULTS",
    BLANKET_TEST_RESULTS: "BLANKET_TEST_RESULTS",
    CERTIFICATION: "CERTIFICATION",
    CERTIFIED_TEST_REPORT: "CERTIFIED_TEST_REPORT",
    CHEMICAL_ANALYSIS: "CHEMICAL_ANALYSIS",
    CHIROPRACTIC_JUSTIFICATION: "CHIROPRACTIC_JUSTIFICATION",
    CONSENT_FORMS: "CONSENT_FORMS",
    CONTINUED_TREATMENT: "CONTINUED_TREATMENT",
    DEATH_NOTIFICATION: "DEATH_NOTIFICATION",
    DENTAL_MODELS: "DENTAL_MODELS",
    DIAGNOSTIC_REPORT: "DIAGNOSTIC_REPORT",
    DISCHARGE_MONITORING: "DISCHARGE_MONITORING",
    DISCHARGE_SUMMARY: "DISCHARGE_SUMMARY",
    DME_PRESCRIPTION: "DME_PRESCRIPTION",
    DRUGS_ADMINISTERED: "DRUGS_ADMINISTERED",
    DRUG_PROFILE: "DRUG_PROFILE",
    EXPLANATION_OF_BENEFITS: "EXPLANATION_OF_BENEFITS",
    FUNCTIONAL_GOALS: "FUNCTIONAL_GOALS",
    HEALTH_CERTIFICATE: "HEALTH_CERTIFICATE",
    HEALTH_CLINIC_RECORDS: "HEALTH_CLINIC_RECORDS",
    IMMUNIZATION_RECORD: "IMMUNIZATION_RECORD",
    INITIAL_ASSESSMENT: "INITIAL_ASSESSMENT",
    JUSTIFICATION_FOR_ADMISSION: "JUSTIFICATION_FOR_ADMISSION",
    LABORATORY_RESULTS: "LABORATORY_RESULTS",
    MEDICAL_HISTORY: "MEDICAL_HISTORY",
    MEDICAL_RECORD_ATTACHMENT: "MEDICAL_RECORD_ATTACHMENT",
    MODELS: "MODELS",
    NURSING_NOTES: "NURSING_NOTES",
    OPERATIVE_NOTE: "OPERATIVE_NOTE",
    ORDERS_TREATMENTS: "ORDERS_TREATMENTS",
    OXYGEN_CONTENT_AVERAGING: "OXYGEN_CONTENT_AVERAGING",
    OXYGEN_THERAPY_CERTIFICATION: "OXYGEN_THERAPY_CERTIFICATION",
    PARAMEDICAL_RESULTS: "PARAMEDICAL_RESULTS",
    PARENTERAL_ENTERAL_CERTIFICATION: "PARENTERAL_ENTERAL_CERTIFICATION",
    PATHOLOGY_REPORT: "PATHOLOGY_REPORT",
    PHOTOGRAPHS: "PHOTOGRAPHS",
    PHYSICAL_EXAMINATION: "PHYSICAL_EXAMINATION",
    PHYSICAL_THERAPY_CERTIFICATION: "PHYSICAL_THERAPY_CERTIFICATION",
    PHYSICAL_THERAPY_NOTES: "PHYSICAL_THERAPY_NOTES",
    PHYSICIAN_ORDER: "PHYSICIAN_ORDER",
    PHYSICIAN_REPORT: "PHYSICIAN_REPORT",
    PLAN_OF_TREATMENT: "PLAN_OF_TREATMENT",
    PRESCRIPTION: "PRESCRIPTION",
    PROGRESS_REPORT: "PROGRESS_REPORT",
    PROSTHETICS_ORTHOTIC_CERTIFICATION: "PROSTHETICS_ORTHOTIC_CERTIFICATION",
    RADIOLOGY_FILMS: "RADIOLOGY_FILMS",
    RADIOLOGY_REPORTS: "RADIOLOGY_REPORTS",
    RECOVERY_PLAN: "RECOVERY_PLAN",
    REFERRAL_FORM: "REFERRAL_FORM",
    RENEWABLE_OXYGEN_CONTENT: "RENEWABLE_OXYGEN_CONTENT",
    REPORT_JUSTIFYING_TREATMENT: "REPORT_JUSTIFYING_TREATMENT",
    STATE_IMMUNIZATION_RECORDS: "STATE_IMMUNIZATION_RECORDS",
    SUPPORT_DATA: "SUPPORT_DATA",
    SYMPTOMS_DOCUMENT: "SYMPTOMS_DOCUMENT",
    TESTS_ANALYSIS_REPORT: "TESTS_ANALYSIS_REPORT",
    TREATMENT_DIAGNOSIS: "TREATMENT_DIAGNOSIS",
};
exports.ProfessionalClaimSubmissionAttachmentTransmissionCode = {
    AVAILABLE_ON_REQUEST: "AVAILABLE_ON_REQUEST",
    BY_FAX: "BY_FAX",
    BY_MAIL: "BY_MAIL",
    ELECTRONICALLY_ONLY: "ELECTRONICALLY_ONLY",
    EMAIL: "EMAIL",
    FILE_TRANSFER: "FILE_TRANSFER",
};
exports.ProfessionalClaimSubmissionEPSDTReferralConditionIndicator = {
    AVAILABLE_NOT_USED: "AVAILABLE_NOT_USED",
    NEW_SERVICE_REQUESTED: "NEW_SERVICE_REQUESTED",
    NOT_USED: "NOT_USED",
    UNDER_TREATMENT: "UNDER_TREATMENT",
};
exports.ProfessionalClaimSubmissionClaimFrequencyCode = {
    CANCELLATION_OF_PRIOR_CLAIM: "CANCELLATION_OF_PRIOR_CLAIM",
    REPLACEMENT_OF_PRIOR_CLAIM: "REPLACEMENT_OF_PRIOR_CLAIM",
};
exports.ProfessionalClaimSubmissionGenderCode = {
    FEMALE: "FEMALE",
    MALE: "MALE",
    UNKNOWN: "UNKNOWN",
};
exports.ProfessionalClaimSubmissionInsuranceType = {
    CHAMPVA: "CHAMPVA",
    FECA_BLK_LUNG: "FECA_BLK_LUNG",
    MEDICAID: "MEDICAID",
    MEDICARE: "MEDICARE",
    OTHER: "OTHER",
    TRICARE: "TRICARE",
};
exports.ProfessionalClaimSubmissionPaymentResponsibilityLevelCode = {
    PRIMARY: "PRIMARY",
};
exports.ProfessionalClaimSubmissionClaimFilingIndicator = {
    AUTOMOBILE_MEDICAL: "AUTOMOBILE_MEDICAL",
    BLUE_CROSS_BLUE_SHIELD: "BLUE_CROSS_BLUE_SHIELD",
    COMMERCIAL_INSURANCE: "COMMERCIAL_INSURANCE",
    DENTAL_MAINTENANCE_ORGANIZATION: "DENTAL_MAINTENANCE_ORGANIZATION",
    DISABILITY: "DISABILITY",
    EXCLUSIVE_PROVIDER_ORGANIZATION: "EXCLUSIVE_PROVIDER_ORGANIZATION",
    FEDERAL_EMPLOYEES_PROGRAM: "FEDERAL_EMPLOYEES_PROGRAM",
    HEALTH_MAINTENANCE_ORGANIZATION: "HEALTH_MAINTENANCE_ORGANIZATION",
    HMO_MEDICARE_RISK: "HMO_MEDICARE_RISK",
    INDEMNITY_INSURANCE: "INDEMNITY_INSURANCE",
    LIABILITY_MEDICAL: "LIABILITY_MEDICAL",
    MEDICAID: "MEDICAID",
    MEDICARE_PART_A: "MEDICARE_PART_A",
    MEDICARE_PART_B: "MEDICARE_PART_B",
    MUTUALLY_DEFINED: "MUTUALLY_DEFINED",
    OTHER_FEDERAL_PROGRAM: "OTHER_FEDERAL_PROGRAM",
    OTHER_NON_FEDERAL_PROGRAMS: "OTHER_NON_FEDERAL_PROGRAMS",
    POINT_OF_SERVICE: "POINT_OF_SERVICE",
    PREFERRED_PROVIDER_ORGANIZATION: "PREFERRED_PROVIDER_ORGANIZATION",
    TITLE_V: "TITLE_V",
    TRICARE: "TRICARE",
    VETERANS_AFFAIRS_PLAN: "VETERANS_AFFAIRS_PLAN",
    WORKERS_COMPENSATION_HEALTH_CLAIM: "WORKERS_COMPENSATION_HEALTH_CLAIM",
};
exports.ProfessionalClaimSubmissionMedicareSecondaryInsuranceType = {
    BLACK_LUNG: "BLACK_LUNG",
    DISABLED_BENEFICIARY_UNDER_AGE_65_WITH_LGHP: "DISABLED_BENEFICIARY_UNDER_AGE_65_WITH_LGHP",
    END_STAGE_RENAL_DISEASE_IN_MANDATED_COORDINATION_PERIOD_WITH_EGHP: "END_STAGE_RENAL_DISEASE_IN_MANDATED_COORDINATION_PERIOD_WITH_EGHP",
    NO_FAULT_INSURANCE_INCLUDING_AUTO_IS_PRIMARY: "NO_FAULT_INSURANCE_INCLUDING_AUTO_IS_PRIMARY",
    OTHER_LIABILITY_INSURANCE_IS_PRIMARY: "OTHER_LIABILITY_INSURANCE_IS_PRIMARY",
    PUBLIC_HEALTH_SERVICE_OR_OTHER_FEDERAL_AGENCY: "PUBLIC_HEALTH_SERVICE_OR_OTHER_FEDERAL_AGENCY",
    VETERANS_ADMINISTRATION: "VETERANS_ADMINISTRATION",
    WORKERS_COMPENSATION: "WORKERS_COMPENSATION",
    WORKING_AGED_BENEFICIARY_OR_SPOUSE_WITH_EGHP: "WORKING_AGED_BENEFICIARY_OR_SPOUSE_WITH_EGHP",
};
exports.ProfessionalClaimSubmissionOtherInsuredRelationshipToInsured = {
    CADAVER_DONOR: "CADAVER_DONOR",
    CHILD: "CHILD",
    EMPLOYEE: "EMPLOYEE",
    LIFE_PARTNER: "LIFE_PARTNER",
    ORGAN_DONOR: "ORGAN_DONOR",
    OTHER_RELATIONSHIP: "OTHER_RELATIONSHIP",
    SELF: "SELF",
    SPOUSE: "SPOUSE",
    UNKNOWN: "UNKNOWN",
};
exports.ProfessionalClaimSubmissionResponsibilityLevel = {
    PRIMARY: "PRIMARY",
    SECONDARY: "SECONDARY",
    TERTIARY: "TERTIARY",
};
exports.ProfessionalClaimSubmissionPatientRelationshipToInsured = {
    CHILD: "CHILD",
    EMPLOYEE: "EMPLOYEE",
    OTHER_RELATIONSHIP: "OTHER_RELATIONSHIP",
    SPOUSE: "SPOUSE",
};
exports.ProfessionalClaimSubmissionPurpose = {
    CHARGEABLE: "CHARGEABLE",
    REPORTING: "REPORTING",
    SUBROGATION_DEMAND: "SUBROGATION_DEMAND",
};
exports.ProfessionalClaimSubmissionDrugIdentificationUnitOfMeasure = {
    GRAM: "GRAM",
    INTERNATIONAL_UNIT: "INTERNATIONAL_UNIT",
    MILLIGRAM: "MILLIGRAM",
    MILLILITER: "MILLILITER",
    UNIT: "UNIT",
};
